Pull request for branch 'addremove' that contains complete To Do app functionality
jkanyi-web/Microverse-ToDo-App pull request #3
Opened 2023-02-24 11:08 UTC by jkanyi-web

Fixed Linter errors
Made file src/index.js that contains functionality for To Do App
Made file src/main.css that contains styling for To Do App
Asjusted contents of src/index.html to accomodate refactored To Do App

2023-02-24 14:18 UTC, emmiiorji requested changes
Hi @jkanyi-web, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Good design
- Repo is professional


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 14:18 UTC, emmiiorji commented on src/index.js
> +/* eslint-disable no-unused-vars */
Kindly ensure that you do not disable linter checks inline. They represent coding standards that you share with your team and most of the time, help to enforce best coding practices.

2023-02-24 14:18 UTC, emmiiorji commented on src/styles/main.css
> +
You have a beautiful design for your todo list. However, launching the project using the dev script (`npm run dev`) does not seem to compile the CSS properly as it does not have styling. This makes it impossible to use the beautiful features you have. Kindly fix this.

I could see the styling on by running the `src/index.html` file in live server.

Project on live server:
![image](https://user-images.githubusercontent.com/20554583/221200538-c5a4f79c-1e7c-4f43-b250-978be09c9bf8.png)

Launching with script:
![image](https://user-images.githubusercontent.com/20554583/221200592-a5269bed-e0ad-45dc-8752-534b556059c1.png)

2023-02-25 12:21 UTC, prolajumokeoni approved these changes
Hi @jkanyi-web 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - All changes requested have been implemented  ✅ 
 - Good todo list app design 👏🏿  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 12:29 UTC, merged

2023-02-25 13:54 UTC, jkanyi-web commented
Hi Emmanuel. Thanks for the feedback and positive response.
My project has not been reviewed for a while now. Can you please also
review the remaining part of the project so I can complete my week?

On Sat, 25 Feb 2023 at 15:21, Oni Olajumoke Priscilla <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @jkanyi-web <https://github.com/jkanyi-web>
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - All changes requested have been implemented ✅
>    - Good todo list app design 👏🏿
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification @prolajumokeoni <https://github.com/prolajumokeoni>.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse-ToDo-App/pull/3#pullrequestreview-1314515674>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5A56DG5KJ2SANX3TPLWZH2NNANCNFSM6AAAAAAVGYRTXI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-25 14:10 UTC, codepantha reviewed
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @jkanyi-web 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 14:10 UTC, codepantha commented on src/index.js
> +};
- [ ] According to requirements, please create a new `js` file imported as a module that contains methods related to the status updates `(completed: true / false)`
- [ ] The functionality to mark a to-do item as completed or not is not working as expected. Currently nothing happens when the checkbox is clicked. Please implement this requirement 🙏

2023-02-25 14:10 UTC, codepantha commented on src/index.js
> +      todos.push(taskInfo);
- [ ] Here, where you create the to-do item, please ensure to be consistent with the keys. In this case, the `index` key is missing. The index is is important especially when you want to delete or update an item. 
- [ ] Also, kindly change the `status` key to `completed` and ensure that it is set to `false` for any new to-do item that is created 👍

2023-02-25 14:10 UTC, codepantha commented on src/index.js
> +});
- [ ] This functionality is meant to delete all to-do items marked as `completed: true` using the `Array.filter()` method. At the moment, you are removing the entire to-do list which is not the expected behaviour.